bubogo: src/bubogo.hs src/Board.hs src/Color.hs src/Coord.hs src/Engine.hs src/Move.hs
	ghc -Wall -cpp -isrc --make src/bubogo.hs -hidir build -odir build -o bubogo

a: src/a.hs
	ghc -cpp -isrc --make src/a.hs -hidir build -odir build -o a
