name:                try-accelerate
version:             0.1.0.0
github:              "dancor/try-accelerate"
license:             BSD3
author:              "Daniel P Corson"
maintainer:          "danl@alum.mit.edu"
copyright:           "© 2019 Daniel P Corson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dancor/try-accelerate#readme>

dependencies:
- base >= 4.7 && < 5
- accelerate ==1.2.0.1
- accelerate-llvm-native ==1.2.0.1
- accelerate-llvm-ptx ==1.2.0.1
- clock
- formatting

library:
  source-dirs: src

executables:
  try-accelerate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-accelerate

tests:
  try-accelerate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-accelerate
